# Site settings
title: agile web development
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  An informative website about software development by Daniel Prinz.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  danielprinz

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

highlighter: rouge
gist:
  noscript: false
